"""Claude Code CLI reviewer for automated code review."""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from lib.config import Config
from lib.log import StructuredLogger


@dataclass(frozen=True)
class ReviewResult:
    """Immutable result of a Claude review."""

    approved: bool
    summary: str
    findings: list[dict[str, Any]] = field(default_factory=list)
    raw_response: str = ""
    parse_error: str | None = None


class ClaudeReviewer:
    """Invokes Claude Code CLI for code review."""

    def __init__(self, config: Config, work_dir: Path, logger: StructuredLogger) -> None:
        self._config = config
        self._work_dir = work_dir
        self._log = logger

    def review(
        self,
        change_name: str,
        openspec_context: str,
        git_diff: str,
    ) -> ReviewResult:
        """Run a full code review via Claude Code CLI."""
        prompt = self._build_review_prompt(change_name, openspec_context, git_diff)
        raw = self._invoke_claude(prompt)
        result = self._parse_review_response(raw)

        log_kwargs: dict = {
            "cycle": 0,  # caller overwrites this
            "approved": result.approved,
            "findings_count": len(result.findings),
        }
        if result.parse_error:
            log_kwargs["parse_error"] = result.parse_error
            log_kwargs["raw_response_preview"] = raw[:500]
        self._log.info("Claude review complete", **log_kwargs)

        return result

    def _build_review_prompt(
        self,
        change_name: str,
        openspec_context: str,
        git_diff: str,
    ) -> str:
        """Build the review prompt with all context."""
        # Truncate diff if extremely large to stay within context limits
        max_diff_chars = 50_000
        truncated_diff = git_diff[:max_diff_chars]
        if len(git_diff) > max_diff_chars:
            truncated_diff += (
                f"\n\n... (truncated, {len(git_diff) - max_diff_chars} chars omitted)"
            )

        return f"""You are a senior software engineer performing a thorough code review of an automated implementation.

The code was generated by an AI agent implementing OpenSpec change "{change_name}". AI-generated code is prone to specific failure modes — be vigilant for those patterns.

# OpenSpec Context (the specification this code must satisfy)
{openspec_context}

# Implementation Changes (git diff)
```diff
{truncated_diff}
```

# Review Checklist

Review every changed file against ALL of the following criteria. Only flag real, concrete issues — not stylistic nitpicks.

## 1. Specification Compliance (CRITICAL — block on any miss)
- Every task in tasks.md is addressed by the diff
- Behavior matches the spec requirements, not just superficially
- Edge cases described in the spec are handled
- No spec requirements silently dropped or partially implemented

## 2. Correctness & Logic (CRITICAL)
- Off-by-one errors, wrong comparison operators, inverted conditions
- Null/undefined access — does the code guard against missing data?
- Race conditions in async code (missing await, unhandled promise rejections)
- State mutations where immutability is expected
- Integer overflow, floating-point comparison, or type coercion bugs
- Dead code paths that can never execute
- Incorrect error propagation (swallowed errors, wrong error types thrown)

## 3. Security (CRITICAL — block on any vulnerability)
- **Injection**: SQL injection (raw string concatenation in queries), XSS (unsanitized user input rendered in HTML/JSX), command injection (user input in shell commands), path traversal (user-controlled file paths without sanitization)
- **Auth**: Missing or bypassed authentication/authorization checks, privilege escalation, IDOR (direct object references without ownership checks)
- **Secrets**: Hardcoded API keys, tokens, passwords, or connection strings in source code
- **Data exposure**: Sensitive data in logs, error messages, or API responses; PII leakage
- **CSRF/CORS**: Missing CSRF tokens on state-changing endpoints, overly permissive CORS
- **Dependency risk**: Known-vulnerable packages, dynamic code execution via string-to-code functions

## 4. Error Handling & Resilience (HIGH)
- External calls (API, DB, filesystem) have proper error handling and timeouts
- User-facing errors are helpful; internal errors don't leak stack traces
- Retry logic has backoff and a max-attempts cap
- Graceful degradation when dependencies are unavailable
- Resource cleanup in error paths (connections, file handles, transactions)

## 5. Data Integrity (HIGH)
- Database migrations are safe and reversible (no data loss on rollback)
- Schema changes are backwards-compatible or have a migration path
- Input validation at system boundaries (API endpoints, form handlers, message consumers)
- Proper transaction boundaries — no partial writes on failure
- Concurrent access patterns handled (optimistic locking, unique constraints)

## 6. Performance (MEDIUM)
- N+1 query patterns (loading related data in a loop instead of a join/batch)
- Missing database indexes on columns used in WHERE, JOIN, or ORDER BY
- Unbounded queries — missing LIMIT or pagination on list endpoints
- Large payloads loaded entirely into memory instead of streamed
- Unnecessary re-renders or re-computations in frontend code

## 7. Testing (MEDIUM)
- New behavior has corresponding tests
- Tests verify behavior, not implementation details
- Edge cases and error paths are tested, not just the happy path
- Mocks are realistic — they don't hide real integration issues
- No flaky test patterns (time-dependent, order-dependent, shared state)

## 8. API & Interface Design (MEDIUM)
- API responses use consistent envelope format
- Breaking changes to existing APIs are flagged
- Request/response types are validated with schemas
- HTTP status codes are semantically correct
- Pagination, filtering, sorting on list endpoints

## 9. Observability (LOW)
- Errors are logged with sufficient context for debugging
- No sensitive data in log output
- Key operations have structured logging or metrics

# Approval Decision

Set `approved: true` ONLY if there are zero critical, high, or medium findings.
Set `approved: false` if ANY critical, high, or medium severity issue exists.

Low findings do not block approval but should still be reported.

Be pragmatic: working code that meets the spec with only minor style issues is approvable. But do NOT approve code with security vulnerabilities, data loss risks, missing spec requirements, or meaningful quality gaps regardless of how minor they seem.

# Response Format

Respond with ONLY a JSON object, no markdown fences, no explanation text:
{{
  "approved": true,
  "summary": "1-2 sentence overall assessment",
  "findings": [
    {{
      "severity": "critical" | "high" | "medium" | "low",
      "category": "spec_compliance" | "correctness" | "security" | "error_handling" | "data_integrity" | "performance" | "testing" | "api_design" | "observability",
      "file": "path/to/file.ext",
      "line": 42,
      "message": "Concrete description of the issue",
      "suggestion": "Specific fix — not vague advice"
    }}
  ]
}}"""

    def _invoke_claude(self, prompt: str) -> str:
        """Invoke Claude Code CLI and return raw response."""
        cmd = ["claude", "-p", prompt, "--output-format", "json"]

        self._log.info("Starting Claude review")

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self._config.review_timeout,
                cwd=str(self._work_dir),
            )

            if result.returncode != 0:
                self._log.warning(
                    "Claude CLI returned non-zero",
                    exit_code=result.returncode,
                    stderr=result.stderr[:500],
                )

            return result.stdout

        except subprocess.TimeoutExpired:
            self._log.warning("Claude review timed out", timeout=self._config.review_timeout)
            return ""
        except FileNotFoundError:
            self._log.error("Claude CLI not found")
            return ""

    def _parse_review_response(self, raw: str) -> ReviewResult:
        """Parse Claude's JSON response into a ReviewResult."""
        if not raw.strip():
            return ReviewResult(
                approved=False,
                summary="No response from Claude CLI",
                parse_error="Empty response",
                raw_response=raw,
            )

        # Claude --output-format json wraps output in a JSON envelope
        # Try parsing the outer envelope first
        try:
            envelope = json.loads(raw)
            # If it's a Claude CLI envelope, extract the result text
            if isinstance(envelope, dict) and "result" in envelope:
                inner = envelope["result"]
            elif isinstance(envelope, dict) and "approved" in envelope:
                # Direct JSON response (no envelope)
                inner = envelope
            else:
                inner = envelope
        except json.JSONDecodeError:
            # Try to find JSON in the raw text
            inner = self._extract_json_from_text(raw)
            if inner is None:
                return ReviewResult(
                    approved=False,
                    summary="Failed to parse review response",
                    findings=[{
                        "severity": "critical",
                        "category": "code_quality",
                        "message": "Failed to parse review response",
                        "suggestion": "Check Claude CLI output format",
                    }],
                    parse_error="Not valid JSON",
                    raw_response=raw[:2000],
                )

        # Parse the inner JSON if it's still a string
        if isinstance(inner, str):
            # Strip markdown code fences and whitespace
            cleaned = inner.strip()
            if cleaned.startswith("```"):
                # Remove opening fence (```json or ```)
                first_newline = cleaned.find("\n")
                if first_newline != -1:
                    cleaned = cleaned[first_newline + 1:]
                # Remove closing fence
                if cleaned.rstrip().endswith("```"):
                    cleaned = cleaned.rstrip()[:-3].rstrip()

            try:
                inner = json.loads(cleaned)
            except json.JSONDecodeError:
                # Try extracting JSON from the text as last resort
                extracted = self._extract_json_from_text(inner)
                if extracted is not None:
                    inner = extracted
                else:
                    return ReviewResult(
                        approved=False,
                        summary="Failed to parse inner review JSON",
                        parse_error="Inner content not valid JSON",
                        raw_response=raw[:2000],
                    )

        if not isinstance(inner, dict):
            return ReviewResult(
                approved=False,
                summary="Unexpected response format",
                parse_error=f"Expected dict, got {type(inner).__name__}",
                raw_response=raw[:2000],
            )

        return ReviewResult(
            approved=bool(inner.get("approved", False)),
            summary=inner.get("summary", "No summary provided"),
            findings=inner.get("findings", []),
            raw_response=raw[:2000],
        )

    def _extract_json_from_text(self, text: str) -> dict[str, Any] | None:
        """Try to extract a JSON object from text that may contain non-JSON content."""
        # Find the first { and last }
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            return None
        try:
            return json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            return None
